# Generated by Django 4.2.25 on 2025-10-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_points', models.IntegerField(default=0)),
                ('player2_points', models.IntegerField(default=0)),
                ('player3_points', models.IntegerField(default=0)),
                ('player4_points', models.IntegerField(default=0)),
                ('board_state', models.JSONField(default=list)),
            ],
        ),
    ]
