# Generated by Django 4.2.25 on 2025-10-31 10:09

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='board_state',
            field=models.JSONField(default=game.models.get_default_board),
        ),
    ]
