# Generated by Django 4.2.25 on 2025-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_gamestate_board_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='board_state',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player1_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player2_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player3_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player4_points',
            field=models.FloatField(default=0.0),
        ),
    ]
